### ISSUE TITLE
Use dynamic target - How to?

### ISSUE THREAD

**Issue by ei02028** [linkedin/hopscotch#105]
Hi guys,

I'm a completely newbie on github and I wasn't able to find help for my problem/doubt. For that, I apologize.

I'm trying to set the target dynamically because I don't have the final id of the element. For that purpose, I'm using "document.querySelector". But isn't working.

Here is my hopscotch code (forget the portuguese):

var tour = {
    id: "AdminChangePasswordAndUsername",
    steps: [
{
    target: document.querySelector('.admintutorialstep1'),
    placement: "left",
    title: "1",
    content: "1"
},
{
    target: document.querySelector('.admintutorialstep2'),
    placement: "left",
    title: "Seleccione a área de administradores",
    content: "Clique no botão da área de administradores"
},
{
    target: document.querySelector('.admintutorialstep3'),
    placement: "left",
    title: "Envie as credenciais",
    content: "Clique no link enviar credenciais e, de seguida, confirme o envio das mesmas"
}
    ]
};

hopscotch.startTour(tour);

If I run the code on chrome, the query selector is able to return something like this:

"<div id="mychildTheme_wt81_block_wtContextNavAndOp_wt54_wtdivBtnSettings" class="NavigationLinkButton admintutorialstep1" onclick="navigate(event, 'mychildTheme_wt81_block_wtContextNavAndOp_wt54_wtlnkNavCalendar')">"

Which means that it should work but it doesn't :)

Can anybody help me? Thanks

**Comment by rsanchez-RA** [comment]
I agree that this should be part of the documentation. Was struggling with this same issue for some time. Thanks @k10world

**Comment by k10world** [comment]
my pleasure :-)
