### ISSUE TITLE
Scroll down is not working and callout is set to invisible

### ISSUE THREAD

**Issue by joaofilipecosta** [linkedin/hopscotch#121]
Hello,

During a tour I have a callout that change its location accordingly with page content.

When there's not much content the callout is shown, but when there's more content the callout is set to invisible.

Shouldn't the page scroll down automatically to where the callout is and show it?

Is this a bug and/or is there any workaround to show the callout?

Thanks,

Joao

**Comment by zimmi88** [comment]
Hi Joao,

Do you have any sample code that reproduces this issue? Are there any particular browsers you're seeing this issue in?

**Comment by zimmi88** [comment]
Closing this issue for now. If there are additional details that can help us reproduce this issue, let us know and we can revisit. Thanks!
