### ISSUE TITLE
Option to add custom html to website tour

### ISSUE THREAD

**Issue by peaceamit** [linkedin/hopscotch#122]
Hi, Is there any way to insert custom html content to hopscotch? As of now, integrating hopscotch with any webpage requires lot of css changes.

**Comment by kate2753** [comment]
Please take a look at this [pull request](https://github.com/linkedin/hopscotch/pull/70). It added support for custom rendering markup of hopscotch callout.

If this information isn't helpful, please add more information and examples to demonstrate the issue you are running into and re-open this ticket.

**Comment by Ankita-G-Mudgal** [comment]
Hi, can I change styles of hopscotch bubble in my component?
