### ISSUE TITLE
Add a className to tour bubbles to allow per tour styling

### ISSUE THREAD

**Issue by electblake** [linkedin/hopscotch#123]
Using the `tour.id` already available, a dynamic class in the format of `tour-<id>` should be added to the bubble element wrapper to allow per tour themeing & tweaks.

This could also be handled through a `hopscotch.templates` approach, but for simple stylings a new template may be overkill.

I suggest implementing this as a final step of the `loadTour()` method

**Comment by zimmi88** [comment]
Linked PR has been merged, so closing this issue.
