### ISSUE TITLE
Close button per step

### ISSUE THREAD

**Issue by iainkfraser** [linkedin/hopscotch#125]
Hello, 

Thanks for hopscotch tour, its a life saver. I was wondering is it possible to disable the close button for a select few steps instead of being toggled for entire tour?

Regards
Iain

**Comment by zimmi88** [comment]
Thanks for the info! Looks like something to consider as part of config cleanup (#67)...

**Comment by kate2753** [comment]
Will be resolved with PR #242

**Comment by kate2753** [comment]
Resolved with #242
