### ISSUE TITLE
Hiding the 'Done' button

### ISSUE THREAD

**Issue by dukedave** [linkedin/hopscotch#145]
Similar to `showNextButton` and `showPrevButton`, should there be a `showDoneButton`?

Alternatively we could have `showNextButton: false`, cause the `Done` button to be hidden on the last step in a tour (where the next button is never shown anyway).

***

My current workaround is to add an unreachable dummy step at the end, where the preceding step `showNextButton: false`.

**Comment by zimmi88** [comment]
`showNextButton: false` on the last step should work to suppress the next button on the last step. The "done" button is actually a "next" button, just that Hopscotch uses a different label if it's the last step of the tour.

Lemme know if the above works for you. I hope this helps!
