### ISSUE TITLE
Can't Tie a Tour Bubble to a DHTMLXWindow

### ISSUE THREAD

**Issue by gfrobenius** [linkedin/hopscotch#148]
(1) Go to this demo: http://dhtmlx.com/docs/products/dhtmlxWindows/samples/01_init/01_minimal_init.html
(2) Click the "Create Window" button.  That is how I am creating my windows.  I want the hopscotch bubble to point to the window.
(3) Hit F12 and type this into the console: document.querySelector('.dhxwin_active')

You can see that selector finds the window.  But the hopscotch bubble doesn't show.  I tried onError with an alert but it is not erroring.  Can hopscotch not work with these types of floating/movable windows?

Thanks!

**Comment by kate2753** [comment]
`'.dhxwin_active'` seems to be a regular DOM element on the page. Hopscotch should be able to work with it just fine. Could you provide more information and maybe some code snippets on how you are creating and starting your hopscotch tour?

**Comment by kate2753** [comment]
It seems to be working fine when I run this in console

To add hopscotch js to the page:
```javascript
var hpjs = document.createElement('script');
hpjs.src = "http://linkedin.github.io/hopscotch/js/hopscotch-0.1.2.min.js";
document.getElementsByTagName('head')[0].appendChild(hpjs);
```
To add hopscotch css to the page:
```javascript
var hpcss = document.createElement('link');
hpcss.rel = "stylesheet";
hpcss.href = "http://linkedin.github.io/hopscotch/css/hopscotch.css";
document.getElementsByTagName('head')[0].appendChild(hpcss);
```
To start a tour:
```javascript
hopscotch.startTour({
        id: 'hopscotch-test-tour',
        steps: [{
          target: '.dhxwin_active',
		  placement: 'bottom',
          title: 'New window',
          content: 'It\'s a new window',
        }]});
```
Here's a screenshot of what I see:
![screen shot 2015-04-01 at 4 24 50 pm](https://cloud.githubusercontent.com/assets/3639923/6954918/1f94cc34-d88c-11e4-9c4a-2b0c280bf1c1.png)

**Comment by gfrobenius** [comment]
It won't work if you start the hopscotch tour before the window is created. That's what I need it to do. I have prior steps, then the window opens, then I need it to point to the window. When the tour starts the window isn't in the DOM yet.

Thanks,
Gordon Frobenius / linkedin

**Comment by kate2753** [comment]
Try passing in target as a selector rather than a DOM element.

```javascript
hopscotch.startTour({
        id: 'hopscotch-test-tour',
        steps: [{
          target: '.dhxwin_active',
          ...
```
vs

**Comment by gfrobenius** [comment]
Duh. Thanks so much!

Thanks,
Gordon Frobenius / linkedin
