### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by stebunovd** [linkedin/hopscotch#150]
That would be really helpful for Browserify and Webpack users if you publish the project to NPM. At the moment it doesn't seem to be there yet https://www.npmjs.com/search?q=hopscotch 

The project already has package.json file, so this should be pretty straightforward - just register at NPM and publish it.

**Comment by stebunovd** [comment]
well, and UMD support will be also needed for this... I could make a PR, but not sure how you prefer to handle jquery dependency. I suppose it could be required for AMD and CommonJS environments, and optional for pure <script> deployments. Or, it could be not required anywhere, and used only if it is available in global window scope.

**Comment by kate2753** [comment]
Hopscotch v0.2.4 has been published to npm

https://www.npmjs.com/package/hopscotch

**Comment by dandv** [comment]
Would really help to list the npm package in [the documentation](http://linkedin.github.io/hopscotch/) and in the README. Its absence is rather unusual.
