### ISSUE TITLE
Sometimes error "Cannot read property 'getBoundingClientRect' of null"

### ISSUE THREAD

**Issue by ArfyFR** [linkedin/hopscotch#157]
Hi,

Sometimes after a page load I got this error.  Especially if the page is "reopen" during browser start.

I saw in code that (example from setPosition: function(step))
600           targetEl     = utils.getStepTarget(step), 
may return null

And the next call to
613       boundingRect = targetEl.getBoundingClientRect(); 
will give this error...

Same problem may occur here
1372           targetBounds   = targetEl.getBoundingClientRect(), 

Remove of a null ?
1554         utils.removeEvtListener(utils.getStepTarget(step), 'click', targetClickNextFn); 

See all getStepTarget calls ;)

**Comment by zimmi88** [comment]
Thanks for the info! We should be sanity checking that `target` actually exists on the page before we end up in `HopscotchBubble` or `adjustWindowScroll`. Well, at least that's the theory, anyway. =/

The code refactoring and cleanup as part of 0.3.0 should help with filtering these issues out of the code base. For now, `getBoundingClientRect` and `removeEvtListener` could use some sanity checks.
