### ISSUE TITLE
New Tag Please

### ISSUE THREAD

**Issue by MHenley** [linkedin/hopscotch#160]
The most recent tag is a bit behind your recent commits which is causing bower to default back to f2473b6 published December 9th 2014.

The code is committed for hopscotch to work out of the box with bower, but we need a more recent tag to use it without forcing bower to pull from master.

**Comment by zimmi88** [comment]
Hi @MHenley,

We should (hopefully) issue a new maintenance release very soon (v. 0.2.4). Issues being tracked for version 0.2.4 are listed on the Milestones page.

https://github.com/linkedin/hopscotch/milestones/0.2.4

I hope this helps!

**Comment by zimmi88** [comment]
Version 0.2.4 was just released and should work with bower. Closing this issue... please let me know if you run into any further issues using Hopscotch with bower. Thanks!
