### ISSUE TITLE
Previous button should sometimes be hidden

### ISSUE THREAD

**Issue by MHenley** [linkedin/hopscotch#161]
If you tell a tour to always show the previous button, it will hide it on the first step, which is great.

If the first step is auto skipped because the element does not exist, the second step will appear as if it's the first step and it will be ordered as step 1.  This is great, except the previous button will be shown, which when clicked just makes the bubbles disappear.

I would propose the previous button on the first visible step should be hidden in the event that the steps are re-ordered.

**Comment by zimmi88** [comment]
Hmm... probably something in the `HopscotchBubble` logic. I'll take a look at this and see what's going on. Thanks for the info!

**Comment by MHenley** [comment]
https://github.com/linkedin/hopscotch/pull/163 was my take on a solution.

**Comment by MHenley** [comment]
I wrote a solution for our fork that resolves this: https://github.com/TechSmith/hopscotch/commit/ee30df1241c3180b43ec4b403262f223f13061c8.

It would be a breaking change though, because if we tell a tour to start at step 5, it no longer allows you to walk backwards to step 4.  I'm holding off on a pull request because I imagine you want a toggle to allow stepping backwards on a tour start, startTour('tourName', 4, false).

**Comment by zimmi88** [comment]
Just submitted out a pull request for this that should keep things backwards compatible. After consulting with @kate2753, we want to utilize `_getStepNum()` to determine the relative step number given skipped steps, since what we care about is hiding the button if it's the relative "first" step.
