### ISSUE TITLE
bower.json not included in releases

### ISSUE THREAD

**Issue by digitalgears** [linkedin/hopscotch#164]
The bower.json file is not included with releases. This means when pulling down a version the .bower.json (not the .) file is generated incorrectly i.e. it doesn't include the "main" section of your bower.json file.

So when using something wiredep, which automatically includes bower_components, it complains it cant find hopscotch.

**Comment by zimmi88** [comment]
Ahh crumbs... Bower by default is pulling the last .tar.gz of the repo auto-generated by GitHub, which is version 0.2.3 (makes sense... most consuming apps probably don't want the latest bleeding edge features on master). `bower.json` was added after that release was generated, so if I'm understanding everything correctly this should resolve itself when we release 0.2.4.

I'm going to group this under the 0.2.4 milestone as something to double-check when we create that release to make sure this is working correctly.

**Comment by zimmi88** [comment]
`bower.json` is now included with releases starting at v.0.2.4. Closing this issue... please lemme know if you run into any further issues with including Hopscotch using bower. Thanks!
