### ISSUE TITLE
skipIfNoElement and nextOnTargetClick combination leads to unhandled exception

### ISSUE THREAD

**Issue by alexyuryev** [linkedin/hopscotch#165]
A tour with skipIfNoElement:true and last step with nextOnTargetClick parameter set to true:
```javascript
hopscotch.startTour({
  id: 'test',
  skipIfNoElement: true,
  steps: [
    {content:'34535', target: 'body', placement:'top', nextOnTargetClick:true},
    {target: 'bla', placement:'top', nextOnTargetClick:true}
  ]
}, 0)
```

Output (after click on document.body):
TypeError: el is null
return el.removeEventListener ? el.removeEventListener(evtName, fn, false) : el....

Version: "0.2.3", as I see still no open issues or fixes

I think it will be better if tour ends without exceptions.

**Comment by ArfyFR** [comment]
Linked with
https://github.com/linkedin/hopscotch/issues/157
and
https://github.com/linkedin/hopscotch/issues/158

with problem that getStepTarget may return null
