### ISSUE TITLE
Step X of Y

### ISSUE THREAD

**Issue by nephiw** [linkedin/hopscotch#173]
I need to display the step number in step x of y format. The x in that formula is i18n.stepNum, but how do I get the number of steps in a tour?

**Comment by zimmi88** [comment]
Hi @nephiw,

We use client-side templates for rendering the contents of each Hopscotch bubble. Part of the data object provided by Hopscotch to the template is the total number of steps in the tour (`tour.numSteps`). This isn't shown as part of the default template, but you can either augment the default template included with Hopscotch or create your own custom template that reads this value... see https://github.com/linkedin/hopscotch/blob/master/src/tl/README.md for details.

FYI, I've noticed we're not providing the i18n value for total number of steps... I've filed issue #175 to address this, to be included as part of our next release.

I hope this helps!

**Comment by nephiw** [comment]
Thanks for getting me an answer. I scoured your documentation for that value without luck.

**Comment by looshi** [comment]
We used Title field to show the step "x of y"  like this : 

for each tour : 
_.each(tour.steps, function(step, index) {
   step.title = (index + 1) + ' of ' + tour.steps.length;
});

We removed the default digit inside the green bubble with css.
