### ISSUE TITLE
Callout Function throws error: Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by txshan** [linkedin/hopscotch#177]
Copied and pasted the exact callout code from the Hopscotch demo to test in my page

    var calloutMgr = hopscotch.getCalloutManager();
    calloutMgr.createCallout({
      id: 'attach-icon',
      target: 'attach-btn',
      placement: 'bottom',
      title: 'Now you can share images &amp; files!',
      content: 'Share a project you\'re proud of, a photo from a recent event, or an interesting presentation.'
    });

this results in Chrome throwing errors: Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

and 

Uncaught Error: Callout by that id already exists. Please choose a unique id.

**Comment by kate2753** [comment]
Thank you for the issue report @txshan . This issue is happening because element that you have specified in target option does not exist on the page, hence Hopsoctch does not know where to position the callout. 

This exception is not helpful though, since it's not telling you what actually happened.  I'll add this issue to our 0.2.5 milestone, to make sure that error message of the exception is more descriptive.

**Comment by txshan** [comment]
Hi @kate2753 , 

Thanks for your feedback. However. The element does exist on the page and is still throwing the error. I tried this with my own callout for my client project as well. I have had no issues with the typical tour, but receive this error with every callout instance I have attempted.

**Comment by kate2753** [comment]
@txshan, could you try running this in the console of your page:

`document.getElementById("attach-icon")`

This is what hopscotch does under the hood to find the target element. If element can't be found using document.getElementById, then Hopscotch would not be able to position the callout.

**Comment by txshan** [comment]
It's located in the console, but not Hopscotch. See screenshot:

![hopscotch](https://cloud.githubusercontent.com/assets/12304355/7596646/e7cfa906-f8b4-11e4-833b-68d90ee50bb6.PNG)

**Comment by kate2753** [comment]
It seems like a timing issue. Your code to create HopscotchCallout must be executing before the element itself is rendered.

Try running this in console after page is loaded:

```
document.getElementById("attach-icon")
```

```
var calloutMgr = hopscotch.getCalloutManager();
```

```
calloutMgr.createCallout({ id: 'attach-icon',   target: 'attach-btn',   placement: 'bottom',  title: 'Now you can share images &amp; files!',   content: 'Share a project you\'re proud of, a photo from a recent event, or an interesting presentation.' });
```

**Comment by txshan** [comment]
![image](https://cloud.githubusercontent.com/assets/12304355/7596963/519919e8-f8b6-11e4-94a4-a31eba96a374.png)



Tried it in a $(window).load(function({});  too and get the same error.

**Comment by kate2753** [comment]
Is there any way you can include unminified version of hopscotch on your page? I'd love to see the stack trace of the exception with line numbers.

You could also try applying the change from pull request #178 to your hopscotch.js file to see if error message you are seeing is changing

**Comment by txshan** [comment]
I used the unminified css and applied the changes from the pull request, and all is well.

**Comment by kate2753** [comment]
Glad to hear that #178 resolves it. Thank you for helping us catch this issue!
