### ISSUE TITLE
Skinning

### ISSUE THREAD

**Issue by Trapulo** [linkedin/hopscotch#180]
I'd like some basic skinning feature, basically change colors of buttons, steps, etc..

**Comment by zimmi88** [comment]
Hi @Trapulo,

The stylesheet for Hopscotch is compiled using LESS. For styling tweaks, I'd recommend pulling this repository, making style changes locally to fit your website, then using Grunt to rebuild Hopscotch. Compiled files should output to the `/tmp` directory... from there, you can copy the final CSS file to another directory.

I hope this helps!
