### ISSUE TITLE
Wordpress and Hopscotch

### ISSUE THREAD

**Issue by diondkb** [linkedin/hopscotch#186]
Hi,

Are there any issues with using Hopscotch on a Wordpress site? The reason I ask is that I manage to duplicate the multipage tutorial outside of Wordpress, but as soon as I create a brand new local wordpress site with minimum plugins installed, the tour does not proceed past step 1.

I have 3 menu items. The first goes nowhere, just starts the tour, which points to the 2nd menu item, and when I click the menu item, the page should change and the tour points to the 3rd menu item. these menu items are visible on all pages.

```
/* globals hopscotch: false */

/* ============ */
/* EXAMPLE TOUR */
/* ============ */
var tour = {
  id: "hdi_episodes",
  steps: [
    {
      title: "Getting Your Podcasts",
      content: "Click on this link ...",
      target: "#menu-item-13",
      placement: "right",
      multipage: true,
      showNextButton: false
    },
    {
      title: "Getting Your Podcasts",
      content: "then Click this link ...",
      target: "menu-item-11",
      placement: "right",
      multipage: true,
      showNextButton: false
//      xOffset: "center",
//      arrowOffset: "center"
    },
   {
      title: "Getting Your Podcasts",
      content: "And we have arrived...",
      target: "this-weeks-lessons.",
      placement: "bottom",
      xOffset: "center",
      arrowOffset: "center"
    }
    
    
  ]
},

/* ========== */
/* TOUR SETUP */
/* ========== */
addClickListener = function(el, fn) {
  if (el.addEventListener) {
    el.addEventListener('click', fn, false);
  }
  else {
    el.attachEvent('onclick', fn);
  }
},

startBtnEl = document.getElementById("menu-item-18");

// Does the start tour button exist
if (startBtnEl) 
{
    addClickListener(startBtnEl, function() 
    {
        if (!hopscotch.isActive) 
        {
            hopscotch.startTour(tour);
        }
    }); 
} 

  
  if (hopscotch.getState() === "hdi_episodes:0" || hopscotch.getState() === "hdi_episodes:1") 
  {
     
    // tour id is hello-hopscotch and we're on the second step. sounds right, so start the tour!
    hopscotch.startTour(tour);
    
  }
  ```
Thanks.

**Comment by zimmi88** [comment]
Hi @diondkb,

Hmm... being a JS library, Hopscotch shouldn't have any opinions about how the page is built, just that it's included on the page and your tour is pointing at valid page elements.

I think your multipage steps, since they're relying on clicking a page element and not the next button, need the `nextOnTargetClick: true` property added. Try adding that property to your multipage steps and see if that works.

**Comment by diondkb** [comment]
Hi,

That seemed to do the trick. Thanks.
