### ISSUE TITLE
No event called after tour is finished

### ISSUE THREAD

**Issue by Tombre** [linkedin/hopscotch#188]
Hi guys, not sure this is a bug or not, but I've noticed that when the `skipIfNoElement` option is set to false, the `onEnd` callback is not called once the final step in a tour is completed (the user clicks "done").

The issue looks like it comes from the `goToStepWithTarget` method, specifically line 1671:
```javascript 
else if (currStepNum + direction >= 0 && currStepNum + direction < currTour.steps.length) {
```
Since by the end of a tour, the tour length is the same length as `currStepNum + direction`, `changeStepCb` is never run and thus the onEnd callbacks are neither.

Is this expected behavior?

**Comment by kate2753** [comment]
@Tombre, thank you for the issue report! This does appear to be a bug. I'm adding it to the 0.2.5 milestone, so we can get a fix out for you.

**Comment by Tombre** [comment]
Thanks Kate!

**Comment by Ettore495** [comment]
FIx this please :(
