### ISSUE TITLE
unable to reactive the tour after wiping out DOM

### ISSUE THREAD

**Issue by jacekgrzybowski** [linkedin/hopscotch#204]
I have a similar issue to #24 using `0.2.5`, however it's not caused by turbolinks. My case - tour start on page load, when user reaches the point when he clicks a certain button by going to next step, the form DOM node is replaced with new content with the HTML response of an ajax call. On ajax success I'm able to call `hopscotch.nextStep()` and then I end up in `onNext()` handler of the last step - which is good. However, I'm unable to bring back the tour by calling `hopscotch.startTour(tour, 2)`. No errors in console, In response I get `Hopscotch` object: `Hopscotch {templates: Object, isActive: true}`

**Comment by zimmi88** [comment]
Merged into #215. Thanks!
