### ISSUE TITLE
Move to next tab in next step

### ISSUE THREAD

**Issue by ajinkyagadewar** [linkedin/hopscotch#208]
When I move to next step for one of the tabs, the tour clock hides automatically and when I refresh the page with that particular tab in the link it shows the block. I tried some jquery in OnNext but it directly switches to tab 2 on page load. 

I am working on this in wordpress.

Can anyone please help me on fixing this issue? 

Thanks.

**Comment by zimmi88** [comment]
Hello!

Sorry, I'm a bit confused by the use case you're working with. It sounds like you have some sort of tabbed layout for the page you're running a tour on... is that accurate?

FWIW, Hopscotch should be agnostic to WordPress, or whichever CMS/framework is used to render the page, so long as Hopscotch is included on the page and there's code to trigger the tour.

**Comment by zimmi88** [comment]
Hello again! Given there hasn't been any updates on this issue for a while, I'm going to close this thread. Please feel free to reopen if the issue persists. Thanks!

**Comment by OlgaPasnin** [comment]
Hi, I have the same issue as the person above. I don't work with WordPress, I think the problem is when you switch between tabs. Is it possible to get around with this issue?
