### ISSUE TITLE
Default arrow offset is used when arrowOffset is set to 0

### ISSUE THREAD

**Issue by timvisee** [linkedin/hopscotch#209]
The arrow offset option isn't working properly, when setting the property o ```0``` it's default value is used instead of ```0```.

The problem happens when setting the following property in a tour step.
```javascript
arrowOffset: 0
```
The arrow offset used is somewhere around ```10```.

It's easy to see this problem is occurring because an offset of ```-1``` or ```1``` clearly moves the arrow towards the zero position, while a value of ```0``` doesn't.

I was using Firefox v41.0b8 while testing this.

**Comment by zimmi88** [comment]
Thanks for the info! We're doing some cleanup on configurations in 0.3.0, so I'll mark this issue for that milestone.

**Comment by timvisee** [comment]
Thanks, I'm looking forward to the fix!

Tim Visée

**Comment by kate2753** [comment]
@timvisee try adding "px" to the value. `arrowOffset: '0px'`.  This might be a quick workaround until we release new version with the fix.

**Comment by kate2753** [comment]
This will be fixed with PR #217

**Comment by kate2753** [comment]
#217 has been merged. Closing this issue.
