### ISSUE TITLE
Multiple reports of startTour() not working after a tour has ended

### ISSUE THREAD

**Issue by zimmi88** [linkedin/hopscotch#215]
Ref: #204, #205, #130 (maybe?).

General theme... attempting to start another tour, or restart a tour previously halted, using startTour() without leaving the page. We'd expect the tour to start, but instead nothing happens.

Hopefully 0.3.0 refactoring should help us figure out what's going on. =)

**Comment by kate2753** [comment]
Should be resolved with #240
