### ISSUE TITLE
Unique selector for each bubble?

### ISSUE THREAD

**Issue by kevzettler** [linkedin/hopscotch#257]
doesn't look like theres any unique selectors for individual bubbles.

there is the `id` option for tours but if I want to write a test or something to target individual bubbles how can I?

**Comment by zimmi88** [comment]
The default bubble template doesn't add any classes or IDs to reflect the current step. If you needed this information, you'd need to create your own custom template or render method to generate the HTML for your tour bubbles, or you could apply a class in the steps `onShow` hook. This might be worth reconsidering for a later milestone, though.

I hope this helps!
