### ISSUE TITLE
startTour() called twice

### ISSUE THREAD

**Issue by mochamadArif** [linkedin/hopscotch#260]
It's my first time using hopscotch to make a tour for my recent project, and then I got something wrong here. `hopscotch.startTour()` called twice when I load the page and then if I set `stepNum`, the `stepNum` always return to 0 in second call when I load the page.

![image](https://cloud.githubusercontent.com/assets/9442005/12195484/1a6087e0-b62a-11e5-93d2-1aa6a668ed90.png)

**Comment by zimmi88** [comment]
Crumbs... this looks like a redux of #130. Hopefully the ES6 Refresh milestone will address this.

Closing as duplicate.
