### ISSUE TITLE
Could someone talk me through adding Hopscotch to my website please?

### ISSUE THREAD

**Issue by hindutimes** [linkedin/hopscotch#264]
Hi there,

I have attempted to follow the instructions on here and on the demo page, but nothing seems to be working.

I've downloaded the hopscotch master file and added it to my ftp.

I've them called in the css and js files in the relevant places in my website (head and body etc).

I've then copied the demo js and changed things around to try to get it to work on my website, but when I add a button with 'startTourBtn' ID, nothing happens.

Could someone help me please? Even just a very quick step by step guide to get something really simple set up, right from the beginning (from downloading the files).

I would really appreciate it, as I'm a hobbyist rather than a professional web designer.

Many thanks,

HT

**Comment by jared-christensen** [comment]
It sounds like you have the right idea. Did you start the tour with hopscotch.startTour(tour)?

If you could show your tour file that would help.

**Comment by tssolutions** [comment]
Hi,

I have the same issue and trying to run very basic tour.
Please guide me to right direction.

Thanks & regards,
Tariq
[tour.zip](https://github.com/linkedin/hopscotch/files/184252/tour.zip)

**Comment by zimmi88** [comment]
Yep, as noted, you'll need to have some code that actually attempts to start the tour, usually by invoking `hopscotch.startTour()`. Given there hasn't been any feedback on this thread for a while, I'm going to close this issue. Please reopen if you're still stuck on this issue. Thanks!
