### ISSUE TITLE
Angularjs example implementation help

### ISSUE THREAD

**Issue by mnemanja** [linkedin/hopscotch#266]
I'm trying to implement hopscotch in my angularjs application, but encountering elements accessibility problems.

Are there any examples how this would be implemented with angularJs?

Help would be much appreciated :)

By the way, am I seeing this wrong, or was the latest release on Jul 21, 2015?

**Comment by cobalthex** [comment]
Here is a pseudo code example:

have a directive that can call a tour service to start:
```html
<button tour-start="test">Start</button>
<div tour-id="test" tour-step="1">...</div>
<div tour-id="test" tour-step="2">...</div>
```

And then a service that can either generate tour steps from a provided json array (1), ajax query (2), or from HTML nodes (3):
```
service Tour:
  Start: fn(name):
  tour = {
    id: name,
    steps: []
  }

  targetElements = $('[tour-id]') //requires jquery or other search method
  
  (1).
  TOURS = {
    test: [ step objects (same as object in docs) with a name or some other identifier, ...]
    other tour ids
  }
  set tour.steps to TOURS[name]
  for each step, set .target to = (filter targetElements to find where .attr('tour-step') == step name (or index/whatever if you want))

  (2).
  same as 1 except fetch tour data from ajax query

  (3).
  have html elements in dom that look something like
  <div tour-id="test" tour-step="1" tour-title="Title">tip content here</div>
  and do a dom query for each
```

**Comment by mnemanja** [comment]
Thanks for the response, 
But since then we've abandoned the hopscotch in our project, so I won't be able to test it any time soon. 

Best of luck.
