### ISSUE TITLE
Silently failing

### ISSUE THREAD

**Issue by mnemanja** [linkedin/hopscotch#267]
I've started implementing Hopscotch in my angularjs app.

First step is the callout, where there is a button to start the tour. Basically this means that at that point everything is done rendering on the page. 

I've created a two step tour where I've provided an ID for the tour element's target. What happens is that the first step gets skipped, even though there is an element with the defined ID.

The problem is that it simply skips it, without providing any information about it.

I've tried applying this property, but it didn't change anything `skipIfNoElement: false`.

**Comment by zimmi88** [comment]
Hopscotch should complain if a target doesn't exist and `skipIfNoElement` is `false`, even during `startTour()`. That's an issue we'll need to track down, though I wouldn't anticipate this getting fixed in the current iteration of Hopscotch (ES6 Refresh would address this instead).

**Comment by chidg** [comment]
I had a similar problem, where after refactoring my (working) code, my Hopscotch tour wouldn't work and wouldn't provide me with any error messages. After a lot of frustration I figured out that the id attribute of the tour object must not contain any dashes (mine was 'person-add-tour'). I changed it to 'person_add_tour' and it started working again.

I hope that helps you @mnemanja
