### ISSUE TITLE
Aggregating Tours

### ISSUE THREAD

**Issue by adis-banda** [linkedin/hopscotch#269]
We are planning to create new feature tours for our product. Each new feature tour will provide a short description of the latest features and will be implemented as a Hopscotch tour with multiple steps. The new features are enabled conditionally for different sets of users so one group of users will have access to feature A, B, C and another group will have access to features A, C. So the problem we are trying to solve is how to create a tour with dynamic content i.e. we need to be able to skip certain steps for users who don't have access to the corresponding feature.

The approach we are considering is to define a tour for each feature and then aggregate them dynamically in the new feature tour depending on the features a user has access to. Please refer to the code samples below.

Has anyone else had to solve this problem and is there a best practice? 

**Individual Feature Tours**

``` javascript
  var tourA = {
    id: 'tourA',
    bubbleWidth: 260,
    steps: [
      {
        target: '#target',
        title: 'Tour A - Step 1',
        content: 'This is the content for Tour A',
        placement: 'left',
        onNext: function() {      
          // A1) Local onNext definition that will be called when user clicks next
        }
      },
      {
        target: '#target',
        title: 'Tour A - Step 2',
        content: 'This is the content for Tour A',
        placement: 'left'
      }
    ],
    onStart: function() {
      var domElem = document.getElementById('domID');
      if(domElem) {
        domElem.click();
      }
    }
  };

  var tourB = {
    id: 'tourB',
    bubbleWidth: 260,
    steps: [
      {
        target: '#target',
        title: 'Tour B - Step 1',
        content: 'This is the content for Tour B',
        placement: 'left',
        onNext: function() {      
          // B1) Local onNext definition that will be called when user clicks next
        }
      },{
        target: '#target',
        title: 'Tour B - Step 2',
        content: 'This is the content for Tour B',
        placement: 'left'
      }
    ],
    onStart: function() {
      var domElem = document.getElementById('domID');
      if(domElem) {
        domElem.click();
      }
    }
  };

```

**(Expected) Aggregated Feature Tour**

``` javascript
  var aggregatedTour = {
    id: 'tourA&tourB',
    bubbleWidth: 260,
    steps: [
      // TOUR A
      {
        target: '#target',
        title: 'Tour A - Step 1',
        content: 'This is the content for Tour A',
        placement: 'left',
        onNext: function() {      
          // A1 onNext 
        }
      },{
        target: '#target',
        title: 'Tour A - Step 2',
        content: 'This is the content for Tour A',
        placement: 'left',
        onNext: function() {      
          // tourB’s onStart
        }
      // TOUR B
      },{
        target: '#target',
        title: 'Tour B - Step 1',
        content: 'This is the content for Tour B',
        placement: 'left',
        onNext: function() {      
          // B1 onNext
        }
      },{
        target: '#target',
        title: 'Tour B - Step 2',
        content: 'This is the content for Tour B',
        placement: 'left'
      }
    ],
    onStart: function() {
      // tourA’s onStart
      var domElem = document.getElementById('domID');
      if(domElem) {
        domElem.click();
      }
    }
  };
```

**Comment by zimmi88** [comment]
Hmm... that's an interesting solution, and it looks reasonable. The two paths I've seen before to solve this have usually been...

- Create separate tours for the various feature combinations you'd anticipate, then selectively pick the tour you want to run. This can work if you have a limited set of audiences or feature combinations for a given tour.
- Include/exclude tour steps depending on feature flags. You could have a backend assemble the tour data for you, or you could pluck tour steps from a superset of all steps before handing the final data set off to Hopscotch.

I hope this helps! I'm going to close this thread since it's not an active issue, but I'll leave it unlocked in case anyone else wants to chime in. Feel free to reopen if you're looking for more feedback.
