### ISSUE TITLE
Tour onError callback doesn't fire on showStep with bad target

### ISSUE THREAD

**Issue by travstone** [linkedin/hopscotch#274]
According to the [use guide](http://linkedin.github.io/hopscotch/), we can provide an `onError()` callback for errors in which the target for a given step is not found. It seems like this callback doesn't fire in the case where the `showStep()` method is used.

CodePen example: http://codepen.io/trav_stone/pen/NNjJjW

After looking at the source briefly, it seems like this might be remedied by adding the following around line 1963 of hopscotch.js ( within the definition of `this.showStep`, in the `if` clause specifying `false` as the value of `utils.getStepTarget(step)` ):

`utils.invokeEventCallbacks('error');`

I'm not incredibly familiar with all the bits and pieces in there however, so perhaps there's a better approach.

If the `onError()` callback _is not_ supposed to work with the `showStep()` method, can someone let me know why? Otherwise I think there's a wee bug in there.

The version I'm working with is hopscotch - v0.2.5

Thanks for an otherwise spectacular library!

Trav

**Comment by travstone** [comment]
Oops- it might also be nice to include the line `currStepNum = stepNum;` right before `utils.invoke...`
It's of interest, to me at least, precisely which step failed.

**Comment by zimmi88** [comment]
Huh... it would make sense that `onError` should work with `showStep()`. I'm guessing `onError` is only currently connected into the `next/prevStep` flow at present. =/

This probably won't be fixed in the current codebase, but the ES6 Refresh milestone should address this issue.

**Comment by travstone** [comment]
Thanks zimmi... I believe I made a simple fix for this in our project, which I'd be happy to turn into a PR at some point, just let me know when/how/where.

**Comment by zimmi88** [comment]
If there's a patch ready to go, I'll consider it for the 0.2.6 maintenance release. (Previously, there wasn't a plan for a maintenance release, but we have enough PRs where it's worth it to make a new release.)

Feel free to submit a PR and I'll take a look. Thanks!

**Comment by travstone** [comment]
I've posted a PR for this, hopefully it's good.
