### ISSUE TITLE
CSS Issues

### ISSUE THREAD

**Issue by cobalthex** [linkedin/hopscotch#276]
1. Everything already has a fully qualified name, there is no need to nest all of your selectors:
`div.hopscotch-bubble .hopscotch-bubble-arrow-container.left .hopscotch-bubble-arrow`
It also makes overriding styles a pain as you now have to have an equally verbose name or use !important for styles to apply.

2. `div.` is unnecessary as there is no special casing based on tag type

3. hopscotch bubble does not need to override font-family or line-height. These are almost always specific to every app and it is more work to now correct these. (These can also be set at the container level and do not need to be set for each individual selector)

4. The default width/padding/etc for tours should be auto. This will allow for said properties to be set in CSS with other styling rules.

**Comment by zimmi88** [comment]
Thanks for reporting! Here's my thoughts on each item in turn...

1. Yeah... we should fix this. That's quite the verbose selector. X_X
2. Also should be fixed. I'm guessing this was there to add some specificity, but we shouldn't be inferring any tag types on this element.
3. IMO, Hopscotch should provide *something* with the repo, but this should be easy to override. I'd like to find a way to separate core styles (things Hopscotch needs to function, such as placement rules) from theme styles (bubble content and look and feel) so it's easy to write styles that help Hopscotch mesh with whichever app it's included with.
4. Ditto. We should assert something by default here, but this should be easy to adapt.

Merging into #290.
