### ISSUE TITLE
Dropdown menu open

### ISSUE THREAD

**Issue by pateljaykesh** [linkedin/hopscotch#277]
Hello Sir,

I want to show tour at bootstrap dropdown submenu. On show event i am toggle dropdown and it will append open class but don't know after hopscotch box show dropdown close.

Please help me on this to resolve this issues.

Thanks

**Comment by zimmi88** [comment]
Sorry, I'm confused... so, you have a dropdown and you want to have it open and close depending on the tour, correct?

I'm unclear on the details of how to integrate with Bootstrap, but it sounds like you're on the right track with toggling using whichever API that provides. On the Hopscotch side of things, you'll want to hook into the `onNext` and/or `onShow` events to open and close the dropdown.

I hope this helps!
