### ISSUE TITLE
Hopscotch 0.2.6 Release Ticket

### ISSUE THREAD

**Issue by zimmi88** [linkedin/hopscotch#289]
This ticket's here to track status of the 0.2.6 release.

Purpose of Release
---------------------------
Maintenance release for 0.2.x master branch. Triage and clear out existing PRs against the master branch. This release should avoid introducing major new features (#197 is a possible exception to this). Unless something urgent comes up or we end up with another significant queue of PRs, this is likely our last 0.2.x release.

Steps
--------
- [x] Create discussion thread for release.
- [x] Triage PRs that will be included in this release.
- [x] Work with PR submitters get all fixes to Ready to Merge status.
- [x] Merge all changes to master.
- [x] `grunt releasePatch`, generate PR, check Travis CI for release health, merge to master.
- [x] Update hopscotch (and jQuery) version on gh-pages.

Call for PRs
----------------
If you have a Pull Request (PR) you'd like to propose for inclusion in this release, please let us know! You can use this thread for general discussion around this release. To make it as part of this release, here's the key dates you'll want to be aware of...

First draft of all PRs posted: **Sunday, June 26th, 8pm PDT**
All PRs merged: **Friday, July 1st, 1pm PDT**
Release pushed to master: **Friday, July 1st, 6pm PDT**
(Note: The release dates provided above may be earlier in the week, depending on our PR progress).

Before submitting a PR, check out the `CONTRIBUTING.md` file for submission details. Also, please note that since we're focused on getting ES6 Refresh ready to go, new features should be saved for that branch and probably won't be merged into master at this time. If you have a PR you'd like to submit, but don't think you could make the timeline published above, do let us know so we can plan accordingly.

Thanks for contributing to Hopscotch!

**Comment by zimmi88** [comment]
Pushing back the release day to July 1st to allow for updating currently posted PRs.

**Comment by zimmi88** [comment]
All done! Marking milestone as resolved. 🎉

**Comment by newtriks** [comment]
Good work, thank you. Could someone push to npm as it appears that there is a version mismatch: <img width="354" alt="screen shot 2016-07-13 at 11 08 29" src="https://cloud.githubusercontent.com/assets/31971/16799735/2cf2c05a-48ea-11e6-9548-053d921793f8.png">

**Comment by zimmi88** [comment]
@newtriks: Done! Sorry... I was making the silly assumption that NPM would pick up the new version from GitHub automatically. =P
