### ISSUE TITLE
Basic implementation silently failing

### ISSUE THREAD

**Issue by cgarveyie** [linkedin/hopscotch#292]
I've created two files, simple.html and simple.js which use the basic code from the demo page and which reference the css and js files in the dist directory.
It is silently failing.
I've added jQuery and have put the hopscotch.startTour call in a $().ready call, just in case it was being executed before hopscotch had been evaluate but that has not helped...Still no error messages.

**Comment by zimmi88** [comment]
Do you have sample code that demonstrates the issue you're running into? Is it literally the same code from the `/demo` folder in the repo? Unfortunately, without more details, I'm unsure what the issue could be.

Hopscotch will end the tour when calling `startTour` if none of the targets for the steps in the tour point to anything on the page. You could try adding an `onError` callback to your tour to see if it ends up getting called.

I hope this helps!
