### ISSUE TITLE
Problem with sticky menu types and Hopscotch

### ISSUE THREAD

**Issue by diondkb** [linkedin/hopscotch#294]
Hi,

The vertical alignment seems to be a problem when using Hopscotch and a sticky menu. Can anyone point me in the right direction. How do i go about correcting this. If possible, maybe include the correction for the benefit of others and not just hack at the core code for my own purposes? I have never really used Git. How would I make this official, should there be a problem with the code in this regard?

Dion

**Comment by zimmi88** [comment]
Duplicates #281, so closing. Let's carry on the discussion over there. Thanks!
