### ISSUE TITLE
Tour stays on same step if using multipage and subsequent step doesn't exist

### ISSUE THREAD

**Issue by yeah** [linkedin/hopscotch#3]
When using a multipage setup, hopscotch works great in case the subsequent step is on the next page. However, it breaks if the subsequent step's target doesn't exist on the next page. I would assume hopscotch would then just "skip" to the next subsequent step, but it doesn't. Instead, it will repeat the last step after the multipage jump.

**Comment by diondkb** [comment]
I have a similar problem when using hopscotch over multiple pages under Wordpress. Cant get passed the first step
