### ISSUE TITLE
We are planning to use in Ember  SPA. Does it can navigate through multiple routes to provide details to user?

### ISSUE THREAD

**Issue by rcramu** [linkedin/hopscotch#309]
Hi,

We are planning to use the framework in one of our projects which is based on  Ember JS. Does it can navigate through multiple routes to provide details to user, automatically?

Thanks.

**Comment by timeiscoffee** [comment]
If its an SPA, you should be able to trigger route changes within hopscotch.

**Comment by zimmi88** [comment]
Yep, your best bet is likely to treat each route change as a multipage hop and pick up the tour again once the route navigation concludes. Changing the URL should suffice for triggering route changes.
