### ISSUE TITLE
hopscotch.startTour(tour) not loading tour in the UI

### ISSUE THREAD

**Issue by AlmogRnD** [linkedin/hopscotch#315]
I have a simple tour inside a meteor react app when I call hopscotch.startTour(tour)  it does not load in the UI. 

I checked to make sure the UI is ready and the elements were rendered. I also checked to make sure hopscotch is getting called and is active. 

Are there any known issues with React?

**Comment by NickHeiner** [comment]
Did you try listening for the `error` event to see if any errors are being fired?

```js
hopscotch.listen('error', onHopscotchError)
```

**Comment by zimmi88** [comment]
No known issues with React specifically. I'd second the recommendation to check and see if any errors are being thrown.
