### ISSUE TITLE
Is Hopscotch still active?

### ISSUE THREAD

**Issue by sharpmachine** [linkedin/hopscotch#316]
Just wondering if the team is still actively working on Hopscotch. I noticed the last commit was in July.

**Comment by zimmi88** [comment]
Plan is still similar to the one outlined in #284. Unfortunately, I don't have a lot of time to devote to Hopscotch at present, so changes are slow going.

At this point, I don't plan to make feature changes to the current code base, instead only fixing critical issues that are pain points for lots of developers. I'm focusing my attention on refactoring and tweaking the API with the time I have. My eventual aspiration is to add a plugin-like API, so the core codebase remains light, but all the various features that are needed on a case-by-case basis can be mixed in by developers that are integrating Hopscotch into their pages. Many items I've seen as feature requests probably wouldn't make it into core, but are perfect candidates for this new plugin system.
