### ISSUE TITLE
Tour restarts on page reload

### ISSUE THREAD

**Issue by risky-boy** [linkedin/hopscotch#317]
I am trying to implement hopscotch in my asp.net application. The bubble reappears on page load.

I have tried   this  [https://www.experts-exchange.com/questions/28968688/Hopscotch-product-tours-Popup-Only-Once-Per-User-and-not-shown-after-page-reload-is-it-possible.html#answer41791127-20](url) solution but it is not working out. Any help is much appreciated! Thanks!

**Comment by zimmi88** [comment]
Sounds like a duplicate of #330? Closing - let me know if this is a different use case.
