### ISSUE TITLE
Scroll container not the body

### ISSUE THREAD

**Issue by rossjcooper** [linkedin/hopscotch#318]
Hi,
I am using hopscotch in my project, the only issue I have is my body is always 100vh and it is a container that is scrollable. This is done as there are some UI elements that are constantly fixed in place and it made sense at the time.
Unfortunately when hopscotch goes to a step that is out of view it causes the body to elongate and scroll instead of the scrollable-container.
Is there anyway I can tell hopscotch to scroll the container rather than the body?
![hopscotch contain bug](https://cloud.githubusercontent.com/assets/3597958/23025748/d928f37c-f456-11e6-9edc-387f0fd7892e.PNG)

**Comment by rossjcooper** [comment]
So I found a similar issue [here ](https://github.com/linkedin/hopscotch/issues/49). I have changed the scroll target to my scrolling container and rebuilt.
It seems better but it still mis-positions the first popup whenever it has to scroll, any after the scroll are positioned fine.

**Comment by rossjcooper** [comment]
So I fixed this by changing my scroll parent in css which looking back was probably a bad decision in general. It would be interesting if there was an option built into future updates.

**Comment by NikhithaSharon** [comment]
could you please add your peace of code here, because am new to this field. 
![hopscotch](https://user-images.githubusercontent.com/48206241/53727832-3a438c80-3e97-11e9-89fd-40faeee39e4d.JPG)

**Comment by NikhithaSharon** [comment]
could you please add your peace of code here, because am new to IT world. 
![hopscotch2](https://user-images.githubusercontent.com/48206241/53728022-aa521280-3e97-11e9-95e6-69062a1db0d6.JPG)

**Comment by afilina** [comment]
@rossjcooper Can you please provide a code snippet of the fix that you did?
