### ISSUE TITLE
Other ways to end tour

### ISSUE THREAD

**Issue by matto2** [linkedin/hopscotch#328]
Is there a way to end the tour other than clicking the little x? 

I would like a way to exit the tour when user clicks anywhere other than the next button ... or clicks on a navigation element.

**Comment by travstone** [comment]
You could wire up your own click handler on whatever you like, and call the endTour method (see http://linkedin.github.io/hopscotch/#api-methods), or something along those lines.

If you do this, might be worth considering that users could accidentally click in one of the locations you mentioned, and end the tour unintentionally- this could be frustrating for the user.

**Comment by zimmi88** [comment]
That response sums things up pretty well. Closing.
