### ISSUE TITLE
Tour not restarting on page reload

### ISSUE THREAD

**Issue by MeenakshiSR** [linkedin/hopscotch#330]
Hi, i'm using hopscotch in my website. After page reload tour is not starting.

**Comment by zimmi88** [comment]
Hopscotch won't start the tour for you on page reload. Presently, it will remember where you were in the tour (and you can get this state by calling `getState()`) but you'll need to give Hopscotch the tour data again via `startTour()` for it to pick up where it left off.

I hope this helps!
