### ISSUE TITLE
bubble not in view when placement set to bottom

### ISSUE THREAD

**Issue by diondkb** [linkedin/hopscotch#338]
Hi,

The bubble is half hidden at the bottom of a webpage when placement is set to bottom. How do I get the page to scroll up so that the bubble is completely visible. Is this an issue or have I not configured something correctly?

Cheers,
Dion

**Comment by zimmi88** [comment]
Hi Dion,

Hopscotch doesn't detect whether a given bubble placement is off of the page. If the bubble is displaying past the bottom of the page, you may want to pick a different bubble position for that particular step.

I hope this helps! If I've misunderstood this issue, please feel free to reopen.

**Comment by sganz** [comment]
I had this problem at one time, and I think I tricked hopscotch by creating an empty div higher up on the page that I tagged it to. It was a hack in my case but worked, not a scrolling solution at all but got it into view.
