### ISSUE TITLE
Support for chaining steps to dynamically loaded content

### ISSUE THREAD

**Issue by hazeltree** [linkedin/hopscotch#48]
Currently building a .NET application built around the single page model. Users interact with the application by click on a navigation link that opens up a popup modal. Unfortunately the content loaded within the modal is called dynamically with AJAX and is not present when Hopscotch is instantiated.

Is there a way to chain steps to selector within the dynamically loaded content? Or perhaps a way to "refresh" Hopscotch so that it has the most current state of the DOM?

Possible related scenario and solution here: http://stackoverflow.com/questions/18897520/hopscotch-js-dynamically-created-modal-target-not-functioning
Is there an official way to accomplish this functionality?

**Comment by zimmi88** [comment]
Rolling into #56.
