### ISSUE TITLE
Break apart JavaScript source into smaller modules

### ISSUE THREAD

**Issue by zimmi88** [linkedin/hopscotch#72]
Now that we have `grunt-include-replace` integrated into our build step (#66), we should look into how we can restructure the `/src/js` directory to have individual components (`HopscotchBubble`, `utils`, `Hopscotch`, and other miscellaneous modules) belong to their own files, which are then concatenated during the build step using `hopscotch.js` as the include-replace template.

Currently, there's a few globals we rely on in the closure that's shared among components. As part of this, we might consider refactoring these into existing or new components.

**Comment by kate2753** [comment]
Work in progress can be found on branch [GH-72](https://github.com/linkedin/hopscotch/tree/gh72/src/es). We are using babel and browserify and re-writing hopscotch in ES2015.

**Comment by kate2753** [comment]
Closing this ticket and will open more issues with specific tasks.
