### ISSUE TITLE
Request: CSS overlays

### ISSUE THREAD

**Issue by henrywright** [linkedin/hopscotch#77]
I'm not sure if it's currently possible, but an overlay effect (where everything on the page is greyed-out except the current step's element) would be a great addition. It would help focus the user's attention on the element being discussed in the current step.

**Comment by vrracing** [comment]
I used DOMlight (https://github.com/h2non/domlight) to get this effect.  There are some tricks noted in this code sample

`      hopscotch.listen('next', () => {
        // get the element hopscotch will target
        let tar = hopscotch.getCurrTarget();

        // if Domlight is highlighting, hideAll.
        // if you hideAll with nothing highlighted, Domlight crashes
        if( Domlight.getActiveElements().length ){
          Domlight.hideAll();
        }

        // highlight the next element
        Domlight( 
          tar, 
          { 
            findOnResize: true,
            hideOnESC: true
          }
        );
      })
      hopscotch.listen('close', () => Domlight.hideAll() )
      hopscotch.listen('end', () => Domlight.hideAll() )
`
