### ISSUE TITLE
[Question] Storing tours in the database

### ISSUE THREAD

**Issue by ysjwang** [linkedin/hopscotch#79]
Got a somewhat philosophical question regarding hopscotch (or click-through tours in general). We're running a Rails application and would like to integrate different hopscotch tours to take users through our application, with some being manually initiated by users and others being auto-initiated. Generally speaking, is there a best-practices way that you guys save (on the database) whether a user has gone through a tour or not?

Thanks!

[sorry, I couldn't figure out how to label this as a question]

**Comment by zimmi88** [comment]
@k10world's solution sounds reasonable. Would depend on your use case how you want to save what tours were shown. IMO, your two key points to hook into would be...

- Impression: On `onStart`, save to the server that the tour has started. Or, when adding the JS to the page that would start the tour, save the impression then.
- Tour completeness: On `onEnd`, save that the tour was completed.

General pattern here would be to use Hopscotch callbacks to make an XHR call to the server to denote what happened.

I hope this helps!
