### ISSUE TITLE
Implement hotscotch on asp.net pages

### ISSUE THREAD

**Issue by coderslife007** [linkedin/hopscotch#9]
I am trying to implement hopscotch on a few asp.net pages. I put the references to the scripts and js in the master file. The problem is that the messagebox keeps flashes for some reason like it is in a loop. Any help would be greatly appreciated.

**Comment by K232** [comment]
Yes, it's already one year old but still on top place in Google so I added this info if someone else has the same problem: In asp.net you should not use a button as it will do a postback and hopscotch does not start then. Instead use a span or something else. See also [Use LinkedIn HopScotch on ASPX Masterpages] (http://dotnetco.de/Blog/ID/52/Use-LinkedIn-HopScotch-on-ASPX-Masterpages.aspx)

**Comment by zimmi88** [comment]
Huh... good to know. Thanks for the info @K232!
